#!/usr/bin/env python

import sys
import requests
from bs4 import BeautifulSoup

def arg_parse():
	num_args = len(sys.argv)
	if num_args == 1:
		return

	keyword = ""

	for i in range(1,num_args):
		if(i == 1):
			keyword = keyword + sys.argv[i]
		else:
			keyword = keyword + "+" + sys.argv[i]

	return keyword

def generate_url():
	keyword = arg_parse()
	times_url = "https://www.latimes.com"
	story_filter = "&t=story"
	url = "https://www.latimes.com/search/?q=" + str(keyword) + story_filter
	return url

def extract_article_url():
	url = generate_url()
	times_url = "https://www.latimes.com"
	page = requests.get(url)
	soup = BeautifulSoup(page.content, 'html.parser')

	try:
		top_url = soup.find('div', class_='h7').find('a', href=True)['href']
	except:
		print("Error: cannot find article related to the provided keyword")
		exit()

	return times_url + top_url

def extract_article_text():

	page = requests.get(extract_article_url())
	soup = BeautifulSoup(page.content, 'html.parser')

	try:
		sentence_list = soup.find('div', class_= "paywall").find("article",class_="grid container padded-container").find('div', class_="wrapper clearfix full pb-feature pb-layout-item pb-f-article-body").find_all('p')
	except:
		print("Error: cannot find article related to the provided keyword")
		exit()

	article = ""
	for element in sentence_list:
		article = article + " " + element.get_text()

	return article

print(extract_article_text())
